# build environment
FROM node:17 as build
WORKDIR /usr/src/app
COPY client/package.json ./
RUN yarn
ADD client ./
RUN yarn build

# production enviornment
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]